#!/usr/bin/env bash
set -euo pipefail

if ! command -v uv >/dev/null 2>&1; then
  echo "uv is required. Install uv first." >&2
  exit 1
fi

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
ROOT_URL="file://$ROOT_DIR"

ENV_ROOT="${ENV_ROOT:-.uv}"
ENV_VLLM="${ENV_VLLM:-$ENV_ROOT/vllm}"
ENV_FILE="${VLLM_ENV_FILE:-$ENV_ROOT/vllm_env.env}"
VLLM_PYTHON="${VLLM_PYTHON:-3.11}"

VLLM_PIP_SPEC="${VLLM_PIP_SPEC:-vllm}"
VLLM_GPTOSS_INSTALL="${VLLM_GPTOSS_INSTALL:-0}"

mkdir -p "$ENV_VLLM"
cat > "$ENV_VLLM/pyproject.toml" <<EOF
[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "evalmt-vllm-env"
version = "0.0.0"
dependencies = [
  "evalmt @ $ROOT_URL"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/evalmt_vllm_env"]
EOF

mkdir -p "$ENV_VLLM/src/evalmt_vllm_env"
: > "$ENV_VLLM/src/evalmt_vllm_env/__init__.py"

echo "==> uv sync --project $ENV_VLLM --python $VLLM_PYTHON"
uv sync --project "$ENV_VLLM" --python "$VLLM_PYTHON"

echo "==> Installing vLLM into $ENV_VLLM"
uv --project "$ENV_VLLM" pip install "$VLLM_PIP_SPEC"

echo "==> Verifying vLLM import"
uv run --project "$ENV_VLLM" python - <<'PY'
import importlib.util
ok = importlib.util.find_spec("vllm") is not None
print("vllm installed:", ok)
if not ok:
    raise SystemExit("vllm import failed")
PY

if [ "$VLLM_GPTOSS_INSTALL" = "1" ]; then
  echo "==> Installing gpt-oss vLLM flavor"
  VLLM_ENV="$ENV_VLLM" ./scripts/install_vllm_gptoss.sh
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup_vllm_env.sh
: "\${UV_PROJECT_SERVE:=$ENV_VLLM}"
export UV_PROJECT_SERVE
EOF

echo "✅ vLLM env ready."
echo "Env file: $ENV_FILE"
echo "Tip: source $ENV_FILE"
