#!/usr/bin/env bash
set -euo pipefail

if ! command -v uv >/dev/null 2>&1; then
  echo "uv is required. Install uv first." >&2
  exit 1
fi

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
ROOT_URL="file://$ROOT_DIR"

ENV_ROOT="${ENV_ROOT:-.uv}"
ENV_COMET="${ENV_COMET:-$ENV_ROOT/comet}"
ENV_METRICX="${ENV_METRICX:-$ENV_ROOT/metricx}"
ENV_BLEU="${ENV_BLEU:-$ENV_ROOT/bleu}"
ENV_FILE="${METRIC_ENV_FILE:-$ENV_ROOT/metric_envs.env}"

# Optional extra pins (comma-separated)
COMET_EXTRA_DEPS="${COMET_EXTRA_DEPS:-}"
METRICX_EXTRA_DEPS="${METRICX_EXTRA_DEPS:-transformers>=4.41.0,tokenizers>=0.15.2}"
BLEU_EXTRA_DEPS="${BLEU_EXTRA_DEPS:-}"

write_project() {
  local dir="$1"
  local name="$2"
  local extra="$3"
  local extra_deps="$4"
  local pkg_name
  pkg_name=$(echo "$name" | tr '-' '_' | tr '.' '_')
  mkdir -p "$dir"
  mkdir -p "$dir/src/$pkg_name"
  : > "$dir/src/$pkg_name/__init__.py"
  local deps_block="  \"evalmt[$extra] @ $ROOT_URL\""
  if [ -n "$extra_deps" ]; then
    IFS=',' read -r -a dep_list <<< "$extra_deps"
    for dep in "${dep_list[@]}"; do
      dep=$(echo "$dep" | xargs)
      if [ -n "$dep" ]; then
        deps_block="${deps_block}\n  \"${dep}\""
      fi
    done
  fi
  cat > "$dir/pyproject.toml" <<EOF
[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "$name"
version = "0.0.0"
dependencies = [
$deps_block
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/$pkg_name"]
EOF
}

sync_project() {
  local dir="$1"
  echo "==> uv sync --project $dir"
  uv sync --project "$dir"
}

echo "Setting up metric envs under $ENV_ROOT"
write_project "$ENV_COMET" "evalmt-comet-env" "comet" "$COMET_EXTRA_DEPS"
write_project "$ENV_METRICX" "evalmt-metricx-env" "metricx" "$METRICX_EXTRA_DEPS"
write_project "$ENV_BLEU" "evalmt-bleu-env" "bleu" "$BLEU_EXTRA_DEPS"

sync_project "$ENV_COMET"
sync_project "$ENV_METRICX"
sync_project "$ENV_BLEU"

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup_metric_envs.sh
: "\${METRIC_UV_PROJECT_COMET:=$ENV_COMET}"
: "\${METRIC_UV_PROJECT_METRICX:=$ENV_METRICX}"
: "\${METRIC_UV_PROJECT_BLEU:=$ENV_BLEU}"
: "\${METRIC_UV_PROJECTS_REQUIRED:=1}"
export METRIC_UV_PROJECT_COMET METRIC_UV_PROJECT_METRICX METRIC_UV_PROJECT_BLEU METRIC_UV_PROJECTS_REQUIRED
EOF

echo "✅ Metric envs ready."
echo "Env file: $ENV_FILE"
echo "Tip: source $ENV_FILE"
